---
api_key:
  type: "string"
  required: true
  default: "apikey"
  description: "API Key"
api_secret:
  type: "string"
  required: true
  default: "api_secret"
  secret: true
region:
  type: "string"
  required: true
  default: "us-east-1"
  description: "API region to use"
private_key_path:
  type: "string"
  required: false
  default: "path/to/nowhere"
  description: "Path to the private key file to use"
