---
name: 001_webhook_trigger.yaml
pack: learnst2
description: "simple rule"
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "sample"

criteria:
  trigger.body.name:
    pattern: "st2" 
    type: "equals"

action:
  ref: "learnst2.say_hello"
  parameters:
    greetings: "echo 'what I can do'"

