---
name: "crontimer_dualfire"
# pack
description: "single trigger =>> dual actions fire" 
enabled: true

trigger:
  type: "core.st2.CronTimer"
  parameters:
    timezone: "America/Los_Angeles"
    day_of_week: "*"
    hour: 17
    minute: 40
    second: 00
action:
  ref: "core.echo"
  parameters:
    message: "Hello World rule" 