---
name: on_hello_event1
pack: learn_stackstorm
description: Sample rule firing on hello_st2.event1.
enabled: true
trigger:
    type: learn_stackstorm.event1
action:
    ref: learn_stackstorm.greet
    parameters:
        greeting: Yo