---
name: on_hello_event1
pack: learnst2
description: Sample rule firing on hello_st2.HelloSensorTrigger.
enabled: true
trigger:
    type: "learnst2.HelloSensorTrigger"
action:
    ref: learnst2.say_hello
    parameters:
      greetings: "{{trigger.greetings}} {{trigger.location}} {{trigger.count}}"
